# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  host: db
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 'postgres'
development:
  <<: *default
  database: New_Billinho_development
test:
  <<: *default
  database: New_Billinho_test
production:
  <<: *default
  database: New_Billinho_production
  